version: "3"
services:
  social-analyzer:
    build: .
    restart: always
    ports:
      - "9005:9005"
    depends_on:
      hub:
        condition: service_started
      firefox:
        condition: service_started
    entrypoint: npm start -- --docker --grid "http://hub:4444/wd/hub"
  hub:
    image: selenium/hub
    restart: always
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 6000
      GRID_TIMEOUT: 6000
  firefox:
    image: selenium/node-firefox
    restart: always
    container_name: web-automation_firefox
    depends_on:
      hub:
        condition: service_started
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: ${CPU_CORES:-2}
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9002:5900"
      - "7900:7900"
